In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("./dataset/house_prices_dataset.csv")

In [5]:
df.head()

   square_feet  num_rooms  age  distance_to_city(km)          price
0  2248.357077          3   92             22.997972  200374.090410
1  1930.867849          2   22             13.984254  268784.847337
2  2323.844269          6   33             21.500945  315020.857676
3  2761.514928          3   63             10.343638  355111.468459
4  1882.923313          7   54             25.485200  234197.123903

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           10000 non-null  float64
 1   num_rooms             10000 non-null  int64
 2   age                   10000 non-null  int64
 3   distance_to_city(km)  10000 non-null  float64
 4   price                 10000 non-null  float64
dtypes: float64(3), int64(2)
memory usage: 390.8 KB

In [12]:
df.tail(5)

      square_feet  num_rooms  age  distance_to_city(km)          price
9995  2650.551032          7    9             18.126034  431344.267823
9996  1000.827516          2   53             24.479692    6650.271134
9997  1647.341638          5   80              2.189312  233698.384301
9998  2247.882787          6   73             27.931014  280766.827379
9999  2322.194227          7   73             10.595721  342895.309114