In [7]:
# pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\faiza\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp314-cp314-win_amd64.whl (8.4 MB)
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.4 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.4 MB 645.0 kB/s eta 0:00:13
   -- ------------------------------------- 0.5/8.4 MB 645.0 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/8.4 MB 694.0 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/8.4 MB 694.0 kB/s eta 0:00:11
   ----- ---------------------------------- 1.0/8.4 MB 732.5 kB/s eta 0:00:11
   ------ --------------------------------- 1.3/8.4 MB 721.3 kB/s eta 0:00:10
   ------ --------------------------------- 1.3/8.4 MB 721.3 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/8.4 MB 756.2 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.4 MB 753.2 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.4 MB 753.2 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.4 MB 753.2 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.4 MB 753.2 kB/s eta 0:00:09
   ---------- ----------------------------- 2.1/8.4 MB 669.3 kB/s eta 0:00:10
   ----------- ---------------------------- 2.4/8.4 MB 682.1 kB/s eta 0:00:09
   ----------- ---------------------------- 2.4/8.4 MB 682.1 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.4 MB 673.7 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.4 MB 673.7 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.4 MB 673.7 kB/s eta 0:00:09
   ------------- -------------------------- 2.9/8.4 MB 659.1 kB/s eta 0:00:09
   ------------- -------------------------- 2.9/8.4 MB 659.1 kB/s eta 0:00:09
   --------------- ------------------------ 3.1/8.4 MB 637.6 kB/s eta 0:00:09
   --------------- ------------------------ 3.1/8.4 MB 637.6 kB/s eta 0:00:09
   ---------------- ----------------------- 3.4/8.4 MB 651.1 kB/s eta 0:00:08
   ----------------- ---------------------- 3.7/8.4 MB 658.5 kB/s eta 0:00:08
   ----------------- ---------------------- 3.7/8.4 MB 658.5 kB/s eta 0:00:08
   ------------------ --------------------- 3.9/8.4 MB 663.6 kB/s eta 0:00:07
   ------------------ --------------------- 3.9/8.4 MB 663.6 kB/s eta 0:00:07
   ------------------ --------------------- 3.9/8.4 MB 663.6 kB/s eta 0:00:07
   -------------------- ------------------- 4.2/8.4 MB 637.7 kB/s eta 0:00:07
   -------------------- ------------------- 4.2/8.4 MB 637.7 kB/s eta 0:00:07
   --------------------- ------------------ 4.5/8.4 MB 639.5 kB/s eta 0:00:07
   --------------------- ------------------ 4.5/8.4 MB 639.5 kB/s eta 0:00:07
   ---------------------- ----------------- 4.7/8.4 MB 639.7 kB/s eta 0:00:06
   ----------------------- ---------------- 5.0/8.4 MB 649.7 kB/s eta 0:00:06
   ------------------------- -------------- 5.2/8.4 MB 664.5 kB/s eta 0:00:05
   -------------------------- ------------- 5.5/8.4 MB 685.0 kB/s eta 0:00:05
   -------------------------- ------------- 5.5/8.4 MB 685.0 kB/s eta 0:00:05
   -------------------------- ------------- 5.5/8.4 MB 685.0 kB/s eta 0:00:05
   --------------------------- ------------ 5.8/8.4 MB 666.3 kB/s eta 0:00:04
   --------------------------- ------------ 5.8/8.4 MB 666.3 kB/s eta 0:00:04
   ---------------------------- ----------- 6.0/8.4 MB 671.8 kB/s eta 0:00:04
   ------------------------------ --------- 6.3/8.4 MB 674.6 kB/s eta 0:00:04
   ------------------------------- -------- 6.6/8.4 MB 696.5 kB/s eta 0:00:03
   -------------------------------- ------- 6.8/8.4 MB 710.7 kB/s eta 0:00:03
   --------------------------------- ------ 7.1/8.4 MB 714.2 kB/s eta 0:00:02
   --------------------------------- ------ 7.1/8.4 MB 714.2 kB/s eta 0:00:02
   ----------------------------------- ---- 7.3/8.4 MB 712.2 kB/s eta 0:00:02
   ----------------------------------- ---- 7.3/8.4 MB 712.2 kB/s eta 0:00:02
   ------------------------------------ --- 7.6/8.4 MB 716.4 kB/s eta 0:00:02
   -------------------------------------- - 8.1/8.4 MB 738.9 kB/s eta 0:00:01
   ---------------------------------------- 8.4/8.4 MB 747.6 kB/s  0:00:11
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl (37.4 MB)
   ---------------------------------------- 0.0/37.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.4 MB ? eta -:--:--
    --------------------------------------- 0.5/37.4 MB 861.6 kB/s eta 0:00:43
    --------------------------------------- 0.8/37.4 MB 1.0 MB/s eta 0:00:37
    --------------------------------------- 0.8/37.4 MB 1.0 MB/s eta 0:00:37
   - -------------------------------------- 1.0/37.4 MB 1.0 MB/s eta 0:00:36
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   - -------------------------------------- 1.3/37.4 MB 1.0 MB/s eta 0:00:35
   -- ------------------------------------- 2.1/37.4 MB 449.9 kB/s eta 0:01:19
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.4/37.4 MB 502.0 kB/s eta 0:01:10
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   -- ------------------------------------- 2.6/37.4 MB 301.3 kB/s eta 0:01:56
   --- ------------------------------------ 2.9/37.4 MB 249.7 kB/s eta 0:02:19
   --- ------------------------------------ 3.1/37.4 MB 269.5 kB/s eta 0:02:07
   --- ------------------------------------ 3.4/37.4 MB 287.6 kB/s eta 0:01:59
   --- ------------------------------------ 3.7/37.4 MB 305.0 kB/s eta 0:01:51
   ---- ----------------------------------- 3.9/37.4 MB 322.8 kB/s eta 0:01:44
   ---- ----------------------------------- 4.2/37.4 MB 340.0 kB/s eta 0:01:38
   ---- ----------------------------------- 4.2/37.4 MB 340.0 kB/s eta 0:01:38
   ---- ----------------------------------- 4.5/37.4 MB 353.9 kB/s eta 0:01:33
   ----- ---------------------------------- 4.7/37.4 MB 369.5 kB/s eta 0:01:29
   ----- ---------------------------------- 4.7/37.4 MB 369.5 kB/s eta 0:01:29
   ----- ---------------------------------- 5.0/37.4 MB 376.5 kB/s eta 0:01:27
   ----- ---------------------------------- 5.0/37.4 MB 376.5 kB/s eta 0:01:27
   ----- ---------------------------------- 5.2/37.4 MB 387.7 kB/s eta 0:01:23
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ----- ---------------------------------- 5.5/37.4 MB 398.0 kB/s eta 0:01:21
   ------ --------------------------------- 6.0/37.4 MB 372.1 kB/s eta 0:01:25
   ------ --------------------------------- 6.0/37.4 MB 372.1 kB/s eta 0:01:25
   ------ --------------------------------- 6.3/37.4 MB 382.0 kB/s eta 0:01:22
   ------ --------------------------------- 6.3/37.4 MB 382.0 kB/s eta 0:01:22
   ------ --------------------------------- 6.3/37.4 MB 382.0 kB/s eta 0:01:22
   ------ --------------------------------- 6.3/37.4 MB 382.0 kB/s eta 0:01:22
   ------ --------------------------------- 6.3/37.4 MB 382.0 kB/s eta 0:01:22
   ------- -------------------------------- 6.6/37.4 MB 372.0 kB/s eta 0:01:23
   ------- -------------------------------- 6.8/37.4 MB 382.6 kB/s eta 0:01:20
   ------- -------------------------------- 6.8/37.4 MB 382.6 kB/s eta 0:01:20
   ------- -------------------------------- 7.1/37.4 MB 388.3 kB/s eta 0:01:18
   ------- -------------------------------- 7.3/37.4 MB 397.7 kB/s eta 0:01:16
   -------- ------------------------------- 7.6/37.4 MB 407.1 kB/s eta 0:01:14
   -------- ------------------------------- 7.9/37.4 MB 416.8 kB/s eta 0:01:11
   -------- ------------------------------- 8.1/37.4 MB 428.0 kB/s eta 0:01:09
   -------- ------------------------------- 8.4/37.4 MB 437.4 kB/s eta 0:01:07
   -------- ------------------------------- 8.4/37.4 MB 437.4 kB/s eta 0:01:07
   --------- ------------------------------ 8.7/37.4 MB 442.8 kB/s eta 0:01:05
   --------- ------------------------------ 8.7/37.4 MB 442.8 kB/s eta 0:01:05
   --------- ------------------------------ 8.9/37.4 MB 445.4 kB/s eta 0:01:04
   --------- ------------------------------ 9.2/37.4 MB 455.1 kB/s eta 0:01:02
   ---------- ----------------------------- 9.4/37.4 MB 460.9 kB/s eta 0:01:01
   ---------- ----------------------------- 9.7/37.4 MB 468.8 kB/s eta 0:01:00
   ---------- ----------------------------- 10.0/37.4 MB 477.0 kB/s eta 0:00:58
   ---------- ----------------------------- 10.2/37.4 MB 484.9 kB/s eta 0:00:56
   ----------- ---------------------------- 10.5/37.4 MB 492.9 kB/s eta 0:00:55
   ----------- ---------------------------- 10.7/37.4 MB 501.2 kB/s eta 0:00:54
   ----------- ---------------------------- 11.0/37.4 MB 509.4 kB/s eta 0:00:52
   ------------ --------------------------- 11.3/37.4 MB 516.7 kB/s eta 0:00:51
   ------------ --------------------------- 11.5/37.4 MB 524.0 kB/s eta 0:00:50
   ------------ --------------------------- 11.8/37.4 MB 528.7 kB/s eta 0:00:49
   ------------ --------------------------- 12.1/37.4 MB 537.5 kB/s eta 0:00:48
   ------------- -------------------------- 12.3/37.4 MB 544.1 kB/s eta 0:00:47
   ------------- -------------------------- 12.6/37.4 MB 551.3 kB/s eta 0:00:45
   ------------- -------------------------- 12.8/37.4 MB 558.3 kB/s eta 0:00:44
   ------------- -------------------------- 12.8/37.4 MB 558.3 kB/s eta 0:00:44
   -------------- ------------------------- 13.1/37.4 MB 561.0 kB/s eta 0:00:44
   -------------- ------------------------- 13.1/37.4 MB 561.0 kB/s eta 0:00:44
   -------------- ------------------------- 13.1/37.4 MB 561.0 kB/s eta 0:00:44
   -------------- ------------------------- 13.4/37.4 MB 557.1 kB/s eta 0:00:44
   -------------- ------------------------- 13.4/37.4 MB 557.1 kB/s eta 0:00:44
   -------------- ------------------------- 13.4/37.4 MB 557.1 kB/s eta 0:00:44
   -------------- ------------------------- 13.4/37.4 MB 557.1 kB/s eta 0:00:44
   -------------- ------------------------- 13.4/37.4 MB 557.1 kB/s eta 0:00:44
   -------------- ------------------------- 13.6/37.4 MB 544.3 kB/s eta 0:00:44
   -------------- ------------------------- 13.9/37.4 MB 549.2 kB/s eta 0:00:43
   -------------- ------------------------- 13.9/37.4 MB 549.2 kB/s eta 0:00:43
   -------------- ------------------------- 13.9/37.4 MB 549.2 kB/s eta 0:00:43
   -------------- ------------------------- 13.9/37.4 MB 549.2 kB/s eta 0:00:43
   --------------- ------------------------ 14.2/37.4 MB 539.7 kB/s eta 0:00:43
   --------------- ------------------------ 14.2/37.4 MB 539.7 kB/s eta 0:00:43
   --------------- ------------------------ 14.4/37.4 MB 542.0 kB/s eta 0:00:43
   --------------- ------------------------ 14.7/37.4 MB 547.2 kB/s eta 0:00:42
   --------------- ------------------------ 14.9/37.4 MB 552.1 kB/s eta 0:00:41
   ---------------- ----------------------- 15.2/37.4 MB 558.6 kB/s eta 0:00:40
   ---------------- ----------------------- 15.5/37.4 MB 564.0 kB/s eta 0:00:39
   ---------------- ----------------------- 15.7/37.4 MB 570.2 kB/s eta 0:00:38
   ----------------- ---------------------- 16.0/37.4 MB 576.2 kB/s eta 0:00:38
   ----------------- ---------------------- 16.3/37.4 MB 578.1 kB/s eta 0:00:37
   ----------------- ---------------------- 16.5/37.4 MB 585.8 kB/s eta 0:00:36
   ----------------- ---------------------- 16.8/37.4 MB 590.1 kB/s eta 0:00:35
   ------------------ --------------------- 17.0/37.4 MB 595.5 kB/s eta 0:00:35
   ------------------ --------------------- 17.3/37.4 MB 600.5 kB/s eta 0:00:34
   ------------------ --------------------- 17.6/37.4 MB 604.4 kB/s eta 0:00:33
   ------------------- -------------------- 17.8/37.4 MB 609.0 kB/s eta 0:00:33
   ------------------- -------------------- 18.1/37.4 MB 612.5 kB/s eta 0:00:32
   ------------------- -------------------- 18.4/37.4 MB 617.7 kB/s eta 0:00:31
   ------------------- -------------------- 18.6/37.4 MB 622.2 kB/s eta 0:00:31
   -------------------- ------------------- 18.9/37.4 MB 627.4 kB/s eta 0:00:30
   -------------------- ------------------- 19.1/37.4 MB 632.9 kB/s eta 0:00:29
   -------------------- ------------------- 19.4/37.4 MB 633.6 kB/s eta 0:00:29
   --------------------- ------------------ 19.9/37.4 MB 642.0 kB/s eta 0:00:28
   --------------------- ------------------ 19.9/37.4 MB 642.0 kB/s eta 0:00:28
   --------------------- ------------------ 20.2/37.4 MB 641.8 kB/s eta 0:00:27
   ---------------------- ----------------- 20.7/37.4 MB 647.2 kB/s eta 0:00:26
   ---------------------- ----------------- 21.0/37.4 MB 712.0 kB/s eta 0:00:24
   ---------------------- ----------------- 21.0/37.4 MB 712.0 kB/s eta 0:00:24
   ---------------------- ----------------- 21.2/37.4 MB 713.7 kB/s eta 0:00:23
   ----------------------- ---------------- 21.8/37.4 MB 724.8 kB/s eta 0:00:22
   ----------------------- ---------------- 22.0/37.4 MB 728.8 kB/s eta 0:00:22
   ----------------------- ---------------- 22.0/37.4 MB 728.8 kB/s eta 0:00:22
   ----------------------- ---------------- 22.3/37.4 MB 727.1 kB/s eta 0:00:21
   ----------------------- ---------------- 22.3/37.4 MB 727.1 kB/s eta 0:00:21
   ------------------------ --------------- 22.8/37.4 MB 733.6 kB/s eta 0:00:20
   ------------------------ --------------- 23.1/37.4 MB 737.9 kB/s eta 0:00:20
   ------------------------ --------------- 23.3/37.4 MB 742.1 kB/s eta 0:00:19
   ------------------------ --------------- 23.3/37.4 MB 742.1 kB/s eta 0:00:19
   ------------------------- -------------- 23.6/37.4 MB 743.4 kB/s eta 0:00:19
   ------------------------- -------------- 23.6/37.4 MB 743.4 kB/s eta 0:00:19
   ------------------------- -------------- 23.9/37.4 MB 727.6 kB/s eta 0:00:19
   ------------------------- -------------- 23.9/37.4 MB 727.6 kB/s eta 0:00:19
   ------------------------- -------------- 23.9/37.4 MB 727.6 kB/s eta 0:00:19
   ------------------------- -------------- 23.9/37.4 MB 727.6 kB/s eta 0:00:19
   ------------------------- -------------- 23.9/37.4 MB 727.6 kB/s eta 0:00:19
   ------------------------- -------------- 24.1/37.4 MB 791.1 kB/s eta 0:00:17
   -------------------------- ------------- 24.6/37.4 MB 801.0 kB/s eta 0:00:16
   -------------------------- ------------- 24.9/37.4 MB 806.8 kB/s eta 0:00:16
   -------------------------- ------------- 24.9/37.4 MB 806.8 kB/s eta 0:00:16
   -------------------------- ------------- 25.2/37.4 MB 802.6 kB/s eta 0:00:16
   --------------------------- ------------ 25.4/37.4 MB 805.7 kB/s eta 0:00:15
   --------------------------- ------------ 25.4/37.4 MB 805.7 kB/s eta 0:00:15
   --------------------------- ------------ 25.4/37.4 MB 805.7 kB/s eta 0:00:15
   --------------------------- ------------ 25.7/37.4 MB 800.1 kB/s eta 0:00:15
   --------------------------- ------------ 25.7/37.4 MB 800.1 kB/s eta 0:00:15
   --------------------------- ------------ 25.7/37.4 MB 800.1 kB/s eta 0:00:15
   --------------------------- ------------ 25.7/37.4 MB 800.1 kB/s eta 0:00:15
   --------------------------- ------------ 25.7/37.4 MB 800.1 kB/s eta 0:00:15
   --------------------------- ------------ 25.7/37.4 MB 800.1 kB/s eta 0:00:15

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: C:\Users\faiza\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [9]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [12]:
df = pd.read_csv("./dataset/Airline satisfaction data.csv")

In [5]:
df.tail()

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
129875,Male,disloyal Customer,34,Business travel,Business,526,3,3,3,1,...,4,4,3,2,4,4,4,0,0.0,False
129876,Male,Loyal Customer,23,Business travel,Business,646,4,4,4,4,...,4,4,4,5,5,5,4,0,0.0,True
129877,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,1,5,...,2,2,4,3,4,5,2,0,0.0,False
129878,Male,Loyal Customer,14,Business travel,Business,1127,3,3,3,3,...,4,4,3,2,5,4,4,0,0.0,True
129879,Female,Loyal Customer,42,Personal Travel,Eco,264,2,5,2,5,...,2,1,1,2,1,1,1,0,0.0,False

In [6]:
df.shape

(129880, 22)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Gender                             129880 non-null  str
 1   Customer Type                      129880 non-null  str
 2   Age                                129880 non-null  int64
 3   Type of Travel                     129880 non-null  str
 4   Class                              129880 non-null  str
 5   Flight Distance                    129880 non-null  int64
 6   Inflight wifi service              129880 non-null  int64
 7   Departure/Arrival time convenient  129880 non-null  int64
 8   Ease of Online booking             129880 non-null  int64
 9   Gate location                      129880 non-null  int64
 10  Food and drink                     129880 non-null  int64
 11  Online boarding                    129880 non-null  int64
 12  Seat comfort                       129880 non-null  int64
 13  Inflight entertainment             129880 non-null  int64
 14  On-board service                   129880 non-null  int64
 15  Leg room service                   129880 non-null  int64
 16  Baggage handling                   129880 non-null  int64
 17  Checkin service                    129880 non-null  int64
 18  Cleanliness                        129880 non-null  int64
 19  Departure Delay in Minutes         129880 non-null  int64
 20  Arrival Delay in Minutes           129487 non-null  float64
 21  satisfaction                       129880 non-null  bool
dtypes: bool(1), float64(1), int64(16), str(4)
memory usage: 20.9 MB

In [8]:
df.columns

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Cleanliness',
       'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='str')

In [9]:
df.index

RangeIndex(start=0, stop=129880, step=1)

In [10]:
df.describe()

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
count,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000
mean,39.427957,1190.316392,2.728696,3.057599,2.756876,2.976925,3.204774,3.252633,3.441361,3.358077,3.383023,3.350878,3.632114,3.306267,3.286326,14.713713,15.091129
std,15.119360,997.452477,1.329340,1.526741,1.401740,1.278520,1.329933,1.350719,1.319289,1.334049,1.287099,1.316252,1.180025,1.266185,1.313682,38.071126,38.465650
min,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,27.000000,414.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,2.000000,0.000000,0.000000
50%,40.000000,844.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,3.000000,0.000000,0.000000
75%,51.000000,1744.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,12.000000,13.000000
max,85.000000,4983.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1592.000000,1584.000000

In [11]:
df.describe(include="all")

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
count,129880,129880,129880.000000,129880,129880,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,...,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000,129880
unique,2,2,NaN,2,3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,Female,Loyal Customer,NaN,Business travel,Business,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
freq,65899,106100,NaN,89693,62160,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73452
mean,NaN,NaN,39.427957,NaN,NaN,1190.316392,2.728696,3.057599,2.756876,2.976925,...,3.441361,3.358077,3.383023,3.350878,3.632114,3.306267,3.286326,14.713713,15.091129,NaN
std,NaN,NaN,15.119360,NaN,NaN,997.452477,1.329340,1.526741,1.401740,1.278520,...,1.319289,1.334049,1.287099,1.316252,1.180025,1.266185,1.313682,38.071126,38.465650,NaN
min,NaN,NaN,7.000000,NaN,NaN,31.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,NaN,27.000000,NaN,NaN,414.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,2.000000,0.000000,0.000000,NaN
50%,NaN,NaN,40.000000,NaN,NaN,844.000000,3.000000,3.000000,3.000000,3.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,3.000000,0.000000,0.000000,NaN
75%,NaN,NaN,51.000000,NaN,NaN,1744.000000,4.000000,4.000000,4.000000,4.000000,...,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,12.000000,13.000000,NaN
max,NaN,NaN,85.000000,NaN,NaN,4983.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1592.000000,1584.000000,NaN

In [12]:
df[["Gender","Customer Type","Age","Type of Travel"]]

        Gender      Customer Type  Age   Type of Travel
0         Male     Loyal Customer   13  Personal Travel
1         Male  disloyal Customer   25  Business travel
2       Female     Loyal Customer   26  Business travel
3       Female     Loyal Customer   25  Business travel
4         Male     Loyal Customer   61  Business travel
...        ...                ...  ...              ...
129875    Male  disloyal Customer   34  Business travel
129876    Male     Loyal Customer   23  Business travel
129877  Female     Loyal Customer   17  Personal Travel
129878    Male     Loyal Customer   14  Business travel
129879  Female     Loyal Customer   42  Personal Travel

[129880 rows x 4 columns]

In [15]:
df = pd.read_csv("./dataset/Airline satisfaction data.csv")

In [16]:
print(df.head())

   Gender      Customer Type  Age   Type of Travel     Class  Flight Distance  \
0    Male     Loyal Customer   13  Personal Travel  Eco Plus              460
1    Male  disloyal Customer   25  Business travel  Business              235
2  Female     Loyal Customer   26  Business travel  Business             1142
3  Female     Loyal Customer   25  Business travel  Business              562
4    Male     Loyal Customer   61  Business travel  Business              214

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4
1                      3                                  2
2                      2                                  2
3                      2                                  5
4                      3                                  3

   Ease of Online booking  Gate location  ...  Seat comfort  \
0                       3              1  ...             5
1                       3              3  ...             1
2                       2              2  ...             5
3                       5              5  ...             2
4                       3              3  ...             5

   Inflight entertainment  On-board service  Leg room service  \
0                       5                 4                 3
1                       1                 1                 5
2                       5                 4                 3
3                       2                 2                 5
4                       3                 3                 4

   Baggage handling  Checkin service  Cleanliness  Departure Delay in Minutes  \
0                 4                4            5                          25
1                 3                1            1                           1
2                 4                4            5                           0
3                 3                1            2                          11
4                 4                3            3                           0

   Arrival Delay in Minutes  satisfaction
0                      18.0         False
1                       6.0         False
2                       0.0          True
3                       9.0         False
4                       0.0          True

[5 rows x 22 columns]

In [17]:
print(df.tail())

        Gender      Customer Type  Age   Type of Travel     Class  \
129875    Male  disloyal Customer   34  Business travel  Business
129876    Male     Loyal Customer   23  Business travel  Business
129877  Female     Loyal Customer   17  Personal Travel       Eco
129878    Male     Loyal Customer   14  Business travel  Business
129879  Female     Loyal Customer   42  Personal Travel       Eco

        Flight Distance  Inflight wifi service  \
129875              526                      3
129876              646                      4
129877              828                      2
129878             1127                      3
129879              264                      2

        Departure/Arrival time convenient  Ease of Online booking  \
129875                                  3                       3
129876                                  4                       4
129877                                  5                       1
129878                                  3                       3
129879                                  5                       2

        Gate location  ...  Seat comfort  Inflight entertainment  \
129875              1  ...             4                       4
129876              4  ...             4                       4
129877              5  ...             2                       2
129878              3  ...             4                       4
129879              5  ...             2                       1

        On-board service  Leg room service  Baggage handling  Checkin service  \
129875                 3                 2                 4                4
129876                 4                 5                 5                5
129877                 4                 3                 4                5
129878                 3                 2                 5                4
129879                 1                 2                 1                1

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
129875            4                           0                       0.0
129876            4                           0                       0.0
129877            2                           0                       0.0
129878            4                           0                       0.0
129879            1                           0                       0.0

        satisfaction
129875         False
129876          True
129877         False
129878          True
129879         False

[5 rows x 22 columns]

In [18]:
print(df.shape)

(129880, 22)

In [19]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Gender                             129880 non-null  str
 1   Customer Type                      129880 non-null  str
 2   Age                                129880 non-null  int64
 3   Type of Travel                     129880 non-null  str
 4   Class                              129880 non-null  str
 5   Flight Distance                    129880 non-null  int64
 6   Inflight wifi service              129880 non-null  int64
 7   Departure/Arrival time convenient  129880 non-null  int64
 8   Ease of Online booking             129880 non-null  int64
 9   Gate location                      129880 non-null  int64
 10  Food and drink                     129880 non-null  int64
 11  Online boarding                    129880 non-null  int64
 12  Seat comfort                       129880 non-null  int64
 13  Inflight entertainment             129880 non-null  int64
 14  On-board service                   129880 non-null  int64
 15  Leg room service                   129880 non-null  int64
 16  Baggage handling                   129880 non-null  int64
 17  Checkin service                    129880 non-null  int64
 18  Cleanliness                        129880 non-null  int64
 19  Departure Delay in Minutes         129880 non-null  int64
 20  Arrival Delay in Minutes           129487 non-null  float64
 21  satisfaction                       129880 non-null  bool
dtypes: bool(1), float64(1), int64(16), str(4)
memory usage: 20.9 MB
None

In [20]:
print(df.describe())

                 Age  Flight Distance  Inflight wifi service  \
count  129880.000000    129880.000000          129880.000000
mean       39.427957      1190.316392               2.728696
std        15.119360       997.452477               1.329340
min         7.000000        31.000000               0.000000
25%        27.000000       414.000000               2.000000
50%        40.000000       844.000000               3.000000
75%        51.000000      1744.000000               4.000000
max        85.000000      4983.000000               5.000000

       Departure/Arrival time convenient  Ease of Online booking  \
count                      129880.000000           129880.000000
mean                            3.057599                2.756876
std                             1.526741                1.401740
min                             0.000000                0.000000
25%                             2.000000                2.000000
50%                             3.000000                3.000000
75%                             4.000000                4.000000
max                             5.000000                5.000000

       Gate location  Food and drink  Online boarding   Seat comfort  \
count  129880.000000   129880.000000    129880.000000  129880.000000
mean        2.976925        3.204774         3.252633       3.441361
std         1.278520        1.329933         1.350719       1.319289
min         0.000000        0.000000         0.000000       0.000000
25%         2.000000        2.000000         2.000000       2.000000
50%         3.000000        3.000000         3.000000       4.000000
75%         4.000000        4.000000         4.000000       5.000000
max         5.000000        5.000000         5.000000       5.000000

       Inflight entertainment  On-board service  Leg room service  \
count           129880.000000     129880.000000     129880.000000
mean                 3.358077          3.383023          3.350878
std                  1.334049          1.287099          1.316252
min                  0.000000          0.000000          0.000000
25%                  2.000000          2.000000          2.000000
50%                  4.000000          4.000000          4.000000
75%                  4.000000          4.000000          4.000000
max                  5.000000          5.000000          5.000000

       Baggage handling  Checkin service    Cleanliness  \
count     129880.000000    129880.000000  129880.000000
mean           3.632114         3.306267       3.286326
std            1.180025         1.266185       1.313682
min            1.000000         0.000000       0.000000
25%            3.000000         3.000000       2.000000
50%            4.000000         3.000000       3.000000
75%            5.000000         4.000000       4.000000
max            5.000000         5.000000       5.000000

       Departure Delay in Minutes  Arrival Delay in Minutes
count               129880.000000             129487.000000
mean                    14.713713                 15.091129
std                     38.071126                 38.465650
min                      0.000000                  0.000000
25%                      0.000000                  0.000000
50%                      0.000000                  0.000000
75%                     12.000000                 13.000000
max                   1592.000000               1584.000000

In [21]:
print(df.isnull().sum())

Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
satisfaction                           0
dtype: int64

In [24]:
for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())

In [47]:
print(df.isnull().sum())

Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [32]:
print(df.columns.tolist())

['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class', 'Flight Distance', 'Inflight wifi service', 'Departure/Arrival time convenient', 'Ease of Online booking', 'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort', 'Inflight entertainment', 'On-board service', 'Leg room service', 'Baggage handling', 'Checkin service', 'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'satisfaction']

In [28]:
df = df.drop_duplicates()

In [35]:
df.columns = df.columns.str.strip()

In [42]:
x = df.drop(columns=["Departure Delay in Minutes", "satisfaction"])
y = df["Departure Delay in Minutes"]

In [46]:
le =LabelEncoder()
y = le.fit_transform(y)

for col in X.select_dtypes(include="object").columns:
le_col = LabelEncoder()
X[col] = le_col.fit_transform(X[col])